# Project information
site_name: 'Isetta Engine'
site_description: 'We are making a game engine and documenting the process'
site_author: 'Caleb, Chaojie, Jacob, Jared, Yidi'
site_url: 'https://isetta.io/'

# Repository
repo_name: 'Isetta Engine'
repo_url: 'https://github.com/Isetta-Team/Isetta-Engine'
edit_uri: ''

# Navigation
nav:
  - Home: index.md
  - About: about.md
  - Team: team.md
  - Schedule: schedule.md
  - Resources: resources.md
  - Glossary: glossary.md
  - FAQ: faq.md
  - Blogs:
    - '[Week 0] Preparation': blogs/week-0.md
    - '[Week 1] The Building Blocks': blogs/week-1.md
    - 'Engine Architecture': blogs/engine-architecture.md
    - '[Week 2] Ramping Up': blogs/week-2.md
    - '[Week 3] "Completing" the Core': blogs/week-3.md
    - '[Week 4] Buried in Comments': blogs/week-4.md
    - '[Week 5] Back in Business': blogs/week-5.md
    - "[Week 6] We Think It's Playable": blogs/week-6.md
    - "[Week 7] A Real Game Engine": blogs/week-7.md
    - "[Week 8] Patching Holes": blogs/week-8.md
    - "[Week 9] Hello from the West Coast": blogs/week-9.md
    - "[Week 10] Grab A Bucket": blogs/week-10.md
    - "[Week 11] The One Where the Team Picks a Font": blogs/week-11.md
    - "[Week 12] Getting Ready for Game Jam!": blogs/week-12.md
    #- Week #: blogs/week-#.md
  - Interviews:
    - Introduction: interviews/introduction.md
    - Shanee Nishry:
      - Interview: interviews/ShaneeNishry-interview.md
      - Video Story: interviews/ShaneeNishry-video.md
    - Jeff Preshing:
      - Interview: interviews/JeffPreshing-interview.md
      - Video Story: interviews/JeffPreshing-video.md
    - Martin Middleton: interviews/MartinMiddleton-interview.md
    # - Jeet Shroff & Florian Strauss: interviews/JeetShroff-FloiranStrauss-interview.md
    # - Elan Ruskin:
    #   - Interview: interviews/ElanRuskin-interview.md
    #   - Video Story: interviews/ElanRuskin-video.md
    - Raymond Graham: 
      - Interview: interviews/RaymondGraham-interview.md
      - Video Story: interviews/RaymondGraham-video.md
    - Aras Pranckevicius: 
      - Interview: interviews/ArasPranckevicius-interview.md
      - Video Story: interviews/ArasPranckevicius-video.md
    - Amandine Coget:
      - Interview: interviews/AmandineCoget-interview.md
      - Video Story: interviews/AmandineCoget-video.md
    - Tommy Refenes:
      - Interview: interviews/TommyRefenes-interview.md
      - Video Story: interviews/TommyRefenes-video.md
    - Casey Muratori:
      - Interview: interviews/CaseyMuratori-interview.md
      - Video Story: interviews/CaseyMuratori-video.md
      - Video Interview: interviews/CaseyMuratori-hmh-video.md
    - Adam Serdar: 
      - Interview: interviews/AdamSerdar-interview.md
      - Video Story: interviews/AdamSerdar-video.md
    - Summarized Advice:
      - Amit Patel & Rob Shillingsburg: interviews/AmitRob-advice.md
      - Jason Gregory: interviews/JasonGregory-advice.md
      - Oliver Franzke: interviews/OliverFranzke-advice.md
      - Walt Destler: interviews/WaltDestler-advice.md
      - Alice Ching: interviews/AliceChing-advice.md
  - Game Jam:
    - FAQs: engine_docs/home.md
    - Basics: engine_docs/basics.md
    - Level: engine_docs/level.md
    - Entity/Transform: engine_docs/entity.md
    - Component: engine_docs/component.md
    - Graphics: engine_docs/graphics.md
    - Input: engine_docs/input.md
    - Debug Logging: engine_docs/debug_logging.md
    - Debug Draw: engine_docs/debug_draw.md
    - GUI: engine_docs/gui.md
    - Audio: engine_docs/audio.md
    - Collisions: engine_docs/collisions.md
    - Networking: engine_docs/networking.md
  - Compendium:
    - Introduction: compendium/introduction.md
    - 3rd Party: compendium/3rdParty.md
    - Build & Resource Management: compendium/Build-ResourceManagement.md
    - Collisions: compendium/Collisions.md
    - Core: compendium/Core.md
    - Gameplay: compendium/Gameplay.md
    - General: compendium/General.md
    - Networking: compendium/Networking.md
    - Scene & Engine Loop: compendium/Scene-Loop.md
    - Tools: compendium/Tools.md

# Configuration
theme:
  name: material
  custom_dir: theme/
  include_sidebar: false
  feature:
    tabs: true
  palette:
    primary: 'light blue'
    accent: 'cyan'
  font:
    text: 'Lato'
    code: 'Source Code Pro'
  favicon: images/isetta_icon.ico
  logo: images/isetta_logo.png

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Copyright
copyright: 'Copyright &copy; 2019 Isetta Team'

# Extra
extra_css:
  - 'extra.css'
extra_javascript:
  - 'extra.js'

extra:
  disqus: 'isetta-engine'
  social:
    - type: envelope
      link: mailto:isetta.engine@gmail.com
    - type: twitter
      link: https://twitter.com/IsettaEngine
    - type: github
      link: https://github.com/Isetta-Team

google_analytics:
  - 'UA-124729724-1'
  - auto