# Project information
site_name: 'Isetta Engine'
site_description: 'We are making a game engine and documenting the process'
site_author: 'Caleb, Chaojie, Jacob, Jared, Yidi'
site_url: 'https://isetta.io/'

# Repository
repo_name: 'Isetta Engine'
repo_url: 'https://github.com/Isetta-Team/Isetta-Engine'
edit_uri: ''

# Navigation
nav:
  - Home: index.md
  - Team: team.md
  - Schedule: schedule.md
  - Resources: resources.md
  - FAQ: faq.md
  - Blogs:
    - '[Week 0] Preparation': blogs/week-0.md
    - '[Week 1] The Building Blocks': blogs/week-1.md
    - 'Engine Architecture': blogs/engine-architecture.md
    #- Week 2: blogs/week-2.md
    #- Week 3: blogs/week-3.md
  - Interviews:
    - Adam Serdar: 
      - Interview: interviews/AdamSerdar-interview.md
      - Video Story: interviews/AdamSerdar-video.md
    - Coming Soon: interviews/coming-soon.md
    #- Person:
    # - Interview: interviews/person-interview.md
    # - Video: interviews/person-video.md

# Configuration
theme:
  name: 'material'
  include_sidebar: false
  feature:
    tabs: true
  palette:
    primary: 'light blue'
    accent: 'cyan'
  font:
    text: 'Lato'
    code: 'Source Code Pro'
  # favicon: assets/images/favicon.png
  logo:
    icon: "memory"

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/Isetta-Team'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Copyright
copyright: 'Copyright &copy; 2019 Isetta Team'

# Extra
extra_css:
  - 'extra.css'

extra:
  disqus: 'isetta-engine'

google_analytics:
  - 'UA-124729724-1'
  - auto